### ISSUE TITLE
CSources2 Duplicate Bug

### ISSUE THREAD

**Issue by jau88** [DirtyBeans/DirtyBeans.github.io#1]
CSources2 does not consider repository duplicates if the protocols differ (ie https://somerepo.com vs http://somerepo.com). Would be great if this could be addressed in the next update.

Also it would be great to be able sort repositories into folder/category subviews, instead of one master list in the application.

Main view / Master List
--> foo  (Folder/category)
     -> repo
     -> repo
--> bar (Folder/category)
    -> repo
    -> repo

**Comment by DirtyBeans** [comment]
Current : CSources2 600.1021-4
In Settings, Search for Duplicates, does show duplicate if http:// vs https://
as for sorting,
Not sure how you would separate sources into folders? please clarify in more detail

**Comment by DirtyBeans** [comment]
Solved, 2017
